---
#this action installs python 3.10 on pull requests
name: python3.10 installer

#this action runs on pull requests
on:
  pull_request:
    branches:
    - main

    #this part tells the program what job to execute when it's run
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # action to checkout repository

    - name: Install Python
      uses: actions/setup-python@v4 #calls on repository with installment of python
      with:
        python-version: '3.10' #this version of python  is installed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


