---
#this action installs python 3.10 on pull requests
name: python3.10 installer

#this action runs on pull requests
on:
  pull_request:
    branches:
    - main

    #this part tells the program what job to execute when it's run
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # action to checkout repository

    #  Caching Python packages
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip   # specify the path where python packages are cached
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }} # cache is uniqe for different os and changes in requirements.txt
        restore-keys: |
          ${{ runner.os }}-pip-


    - name: Install Python
      uses: actions/setup-python@v4 # calls on repository with installation of Python
      with:
        python-version: '3.10' # this version of Python is installed


    - name: Install dependencies  # Install the reqirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: pre-commit
      uses: pre-commit/action@v3.0.0

    - name: Run Tests
      run: |
        py.test tests/

